name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build-deb-linux:
    name: Build Project and Pack It
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'
          cache: 'maven'
      - name: Build
        run: mvn clean package
      - name: Echo
        run: echo "$PWD"
