name: Build and Package

on:
  push:

# Only trigger when a commit is pushed with tag starts with v.

env:
  packageName: githubactspackage-1.0-SNAPSHOT.jar
  appName: Test Hello
  appDir: app
  linuxCategory: Game
  version: 1.1.9
  vendor: etkmlm
  javaVersion: 22
  javaSource: zulu

jobs:
  build:
    name: Build and JARify Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.javaSource}}
          java-version: ${{env.javaVersion}}
          cache: 'maven'
      - name: Build
        run: mvn clean package shade:shade
      - name: Cache JAR
        uses: actions/cache/save@v4
        with:
          path: "target/${{env.packageName}}"
          key: jarpack
          save-always: true
  cacheRestore:
    name: Restore Test Cache
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Restore
        uses: actions/cache/restore@v4
        with:
          key: jarpack
          path: app/main.jar
      - name: Print
        run: cd app && ls
