name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build-deb-linux:
    name: Build Project and Pack It
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'
          cache: 'maven'
      - name: Build
        run: mvn clean package shade:shade
      - name: Install jpackage dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev fakeroot dpkg-dev
      - name: Run jpackage
        run: jpackage --name "Test" --type deb --input target --main-jar githubactspackage-1.0-SNAPSHOT.jar --app-version 1.1.9 --vendor etkmlm --java-options "'-Duser.dir=\$APPDIR'" --linux-menu-group Game
