name: Build and Package

on:
  push:

# Only trigger when a commit is pushed with tag starts with v.

env:
  packageName: githubactspackage-1.0-SNAPSHOT.jar
  appName: Test Hello
  appDir: app
  linuxCategory: Game
  version: 1.1.9
  vendor: etkmlm
  javaVersion: 22
  javaSource: zulu

jobs:
  build:
    name: Build and JARify Project
    runs-on: ubuntu-latest
    steps:
      - name: Check Cache
        if: steps.cache.outputs.cache-hit != true
      - name: Checkout
        continue-on-error: false
        uses: actions/checkout@v4
      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.javaSource}}
          java-version: ${{env.javaVersion}}
          cache: 'maven'
      - name: Build
        continue-on-error: false
        run: mvn clean package shade:shade
      - name: Cache JAR
        continue-on-error: false
        id: cache
        uses: actions/cache/save@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
  cacheRestore:
    name: Restore Test Cache
    runs-on: mac-latest
    needs: [build]
    steps:
      - name: Restore
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
      - name: Print
        run: cd target && ls
