name: Build and Package

on:
  push:

# Only trigger when a commit is pushed with tag starts with v.

env:
  packageName: githubactspackage-1.0-SNAPSHOT.jar
  appName: Test Hello
  appDir: app
  linuxCategory: Game
  linuxPackageName: test-hello
  version: 1.1.91
  vendor: etkmlm
  javaVersion: 17
  javaSource: zulu

jobs:
  check-cache:
    name: Check JAR Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{steps.get-cache.outputs.cache-hit}}
    steps: 
      - id: get-cache
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
  build:
    name: Build and Create JAR File
    needs: [check-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: needs.check-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
      - name: Install Java
        if: needs.check-cache.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.javaSource}}
          java-version: ${{env.javaVersion}}
          java-package: jdk+fx
          cache: 'maven'
      - name: Build
        if: needs.check-cache.outputs.cache-hit != 'true'
        run: mvn clean package shade:shade
      - name: Cache JAR
        id: cache
        if: always() && needs.check-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
  pack-deb-linux:
    needs: [build]
    if: false
    name: Pack JAR For Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install jpackage Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev fakeroot dpkg-dev
      - name: Get Cached JAR
        id: get-cache
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.javaSource}}
          java-version: ${{env.javaVersion}}
          java-package: jre+fx
      - name: Prepare Files
        run: mkdir app && cp "target/${{env.packageName}}" app/main.jar
      - name: Run jpackage
        id: jprun
        run: jpackage --name "${{env.appName}}" --type deb --input "${{env.appDir}}" --main-jar main.jar --app-version "${{env.version}}" --vendor "$vendor" --java-options "'-Duser.dir=\$APPDIR'" --linux-menu-group "${{env.linuxCategory}}" && echo "file=$( ls -Art | tail -n 1 )" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-package-${{env.version}}
          path: ${{steps.jprun.outputs.file}}
  pack-exe-windows:
    needs: [build]
    name: Pack JAR For Windows
    runs-on: windows-latest
    steps:
      - name: Get JAR Cache
        id: get-cache
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
      - name: Get Java Cache
        id: get-java-cache
        uses: actions/cache/restore@v4
        with:
          path: java/*
          key: win-java
      - name: Java Procession
        if: steps.get-java-cache.outputs.cache-hit != true
        uses: actions/github-script@v7
        with:
          script: |
            const jdkUrl = "https://api.azul.com/metadata/v1/zulu/packages/?java_version=${{env.javaVersion}}&os=linux&arch=x64&java_package_type=jdk&javafx_bundled=true&release_status=ga&availability_types=CA&archive_type=tar.gz&certifications=tck&latest=true";
            const jreUrl = "https://api.azul.com/metadata/v1/zulu/packages/?java_version=${{env.javaVersion}}&os=linux&arch=x64&java_package_type=jre&javafx_bundled=true&release_status=ga&availability_types=CA&archive_type=tar.gz&certifications=tck&latest=true";
            const jdkResult = await fetch(jdkUrl).then(x => x.json());
            const jreResult = await fetch(jreUrl).then(x => x.json());

            const fs = require('fs');
            const stream = require('stream');
            exec.exec('mkdir java');
            
            const fetchJdk = await fetch(jdkResult[0].download_url);
            if (fetchJdk.ok && fetchJdk.body){
              let writer = fs.createWriteStream("java/jdk.tar.gz");
              stream.Readable.fromWeb(fetchJdk.body).pipe(writer);
              console.log("JDK downloaded.");
            }
            else{
              core.setFailed('JDK could not be downloaded.');
              return;
            }

            const fetchJre = await fetch(jreResult[0].download_url);
            if (fetchJre.ok && fetchJre.body){
              let writer = fs.createWriteStream('java/jre.tar.gz');
              stream.Readable.fromWeb(fetchJre.body).pipe(writer);
              console.log("JRE downloaded.");
            }
            else{
              core.setFailed('JRE could not be downloaded.');
            }
      - name: Save Java Cache
        if: steps.get-java-cache.outputs.cache-hit != true
        uses: actions/cache/save@v4
        with:
          path: java/*
          key: win-java
  pack-dmg-macos-old:
    needs: [build]
    if: false
    name: Pack JAR For MacOS Non Apple Silicon
    runs-on: macos-13
    steps:
      - name: Get Cache
        id: get-cache
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.javaSource}}
          java-version: ${{env.javaVersion}}
          java-package: jre+fx
      - name: Copy Files
        run: mkdir app && cp "target/${{env.packageName}}" app/main.jar
      - name: Run jpackage
        id: jprun
        shell: bash
        run: jpackage --name "${{env.appName}}" --type dmg --input "${{env.appDir}}" --main-jar main.jar --app-version "${{env.version}}" --vendor "${{env.vendor}}" --java-options "'-Duser.dir=\$APPDIR'" --mac-package-name "${{env.appName}}" && echo "file=$( ls -Art | tail -n 1 )" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-old-package-${{env.version}}
          path: ${{steps.jprun.outputs.file}}
  pack-dmg-macos:
    needs: [build]
    if: false
    name: Pack JAR For MacOS Apple Silicon
    runs-on: macos-latest
    steps:
      - name: Get Cache
        id: get-cache
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.javaSource}}
          java-version: ${{env.javaVersion}}
          java-package: jre+fx
      - name: Copy Files
        run: mkdir app && cp "target/${{env.packageName}}" app/main.jar
      - name: Run jpackage
        id: jprun
        shell: bash
        run: jpackage --name "${{env.appName}}" --type dmg --input "${{env.appDir}}" --main-jar main.jar --app-version "${{env.version}}" --vendor "${{env.vendor}}" --java-options "'-Duser.dir=\$APPDIR'" --mac-package-name "${{env.appName}}" && echo "file=$( ls -Art | tail -n 1 )" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-package-${{env.version}}
          path: ${{steps.jprun.outputs.file}}
  
