name: Build and Package

on:
  push:

# Only trigger when a commit is pushed with tag starts with v.

env:
  packageName: githubactspackage-1.0-SNAPSHOT.jar
  appName: Test Hello
  appDir: app
  linuxCategory: Game
  linuxPackageName: test-hello
  version: 1.1.9
  vendor: etkmlm
  javaVersion: 22
  javaSource: zulu

jobs:
  check-cache:
    name: Check the artifact cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{steps.get-cache.outputs.cache-hit}}
    steps: 
      - name: Get Cache
        id: get-cache
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
      - run: echo "file=$( ls -Art | tail -n 1 )"
  build:
    name: Build and JARify Project
    needs: [check-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: needs.check-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
      - name: Installing Java
        if: needs.check-cache.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.javaSource}}
          java-version: ${{env.javaVersion}}
          cache: 'maven'
      - name: Build
        if: needs.check-cache.outputs.cache-hit != 'true'
        run: mvn clean package shade:shade
      - name: Cache JAR
        id: cache
        if: always() && needs.check-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
  pack-deb-linux:
    needs: [build]
    name: Pack The JAR For Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install jpackage dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev fakeroot dpkg-dev
      - name: Get Cache
        id: get-cache
        uses: actions/cache/restore@v4
        with:
          path: target/${{env.packageName}}
          key: jarpack-${{env.version}}
          enableCrossOsArchive: true
      - name: Copy Files
        run: mkdir app && cp "target/${{env.packageName}}" app/main.jar
      - name: Run jpackage
        id: jprun
        run: jpackage --name "${{env.appName}}" --type deb --input "${{env.appDir}}" --main-jar main.jar --app-version "${{env.version}}" --vendor "$vendor" --java-options "'-Duser.dir=\$APPDIR'" --linux-menu-group "${{env.linuxCategory}}" && echo "file=${ls -Art | tail -n 1}" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.jprun.outputs.file}}
          path: ${{env.version}}/linux/${{steps.jprun.outputs.file}}
  
